// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYlLLLROx0SFUQDXe15qdIyh0XM-ATOU8',
    appId: '1:1034156484558:web:8382a2ef7e2660bff16d9f',
    messagingSenderId: '1034156484558',
    projectId: 'my-task-manager-7cebf',
    authDomain: 'my-task-manager-7cebf.firebaseapp.com',
    storageBucket: 'my-task-manager-7cebf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRdJaypZ_RUgQGbG6W9Sfas4FF-oLgso4',
    appId: '1:1034156484558:android:f90113adf6d0b09cf16d9f',
    messagingSenderId: '1034156484558',
    projectId: 'my-task-manager-7cebf',
    storageBucket: 'my-task-manager-7cebf.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeZTisvHST3KTNJKLCbFNaJcn1cxtEv9w',
    appId: '1:1034156484558:ios:d1e9d5c28ec53190f16d9f',
    messagingSenderId: '1034156484558',
    projectId: 'my-task-manager-7cebf',
    storageBucket: 'my-task-manager-7cebf.firebasestorage.app',
    iosBundleId: 'com.example.mytaskmanager',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeZTisvHST3KTNJKLCbFNaJcn1cxtEv9w',
    appId: '1:1034156484558:ios:d1e9d5c28ec53190f16d9f',
    messagingSenderId: '1034156484558',
    projectId: 'my-task-manager-7cebf',
    storageBucket: 'my-task-manager-7cebf.firebasestorage.app',
    iosBundleId: 'com.example.mytaskmanager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYlLLLROx0SFUQDXe15qdIyh0XM-ATOU8',
    appId: '1:1034156484558:web:ba7ad1c52584594ef16d9f',
    messagingSenderId: '1034156484558',
    projectId: 'my-task-manager-7cebf',
    authDomain: 'my-task-manager-7cebf.firebaseapp.com',
    storageBucket: 'my-task-manager-7cebf.firebasestorage.app',
  );
}
